
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "ubuntu_dockerhost"
    end
    config.vm.network "private_network", type: "dhcp" ##This is to define dhcp
    dockerhost.vm.provision "shell",
        inline: "apt-get update && apt-get install -y docker.io"
  end

end
