Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host:8089
    ##config.vm.network "private_network", ip: "192.168.50.4" ##Configure to static ip
    ##config.vm.network "private_network", type: "dhcp" ##This is to define dhcp
    config.vm.network "public_network"## Allow acess VM to public network
end